name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes no modo headless
        run: npx cypress run

      - name: Upload de screenshots e vídeos em caso de falha
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots
          retention-days: 5
